### ISSUE TITLE
More permissive licence for icons

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/puppy_icon_theme#1]
I'll leave this up to anyone but @technosaurus may have some ideas for the licence.

Whatever is chosen will also have to be integrated into woof-CE as most of the icons come from `/usr/share/pixmaps/puppy/`

**Comment by technosaurus** [comment]
I put in pull request #2 with the relicense and some fixes.

**Comment by 01micko** [comment]
fixed with #2
