### ISSUE TITLE
xlink is not always defined

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/puppy_icon_theme#3]
In some icons (inode-chardevice.svg, spell-check.svg) xmlns:xlink is defined in the <svg> tag attributes while in others (internet_connect*.svg, networkboth.svg) is not.
Lack of [name space declaration](https://developer.mozilla.org/en/docs/Web/SVG/Namespaces_Crash_Course) may result in failures in apps/environments that adhere to protocols more strictly.

**Comment by 01micko** [comment]
For simplicity, I will probably remove all `xlink` lines and redo gradients and glyphs affected.

**Comment by 01micko** [comment]
Ok, have fixed the script so that if xlink is defined then it is carried over. I was too lazy to draw paths for the glyphs! I'll close this but feel free to re-open if there is still a problem.
