### ISSUE TITLE
Negative height/width not allowed

### ISSUE THREAD

**Issue by technosaurus** [puppylinux-woof-CE/puppy_icon_theme#4]
Some icons have negative height/width values which is [https://www.w3.org/TR/SVG/shapes.html#RectElementHeightAttribute](not allowed)

quality_*.svg
sound_eq.svg

I made a tool to convert rectangles to paths, but I kind-of expected the rectangles to conform to the spec.  I'm not sure what the intent was.

**Comment by 01micko** [comment]
I suppose these should be remade with paths. Or would you like the icons fixed with positive `<rect ...>` values to test your script?

**Comment by 01micko** [comment]
Your script should work now.
