### ISSUE TITLE
viewBox vs viewbox

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/puppy_icon_theme#5]
Some icons (add, application-pet, application-rtf, application-x-compressed-tar) use `viewBox="<min-x> <min-y> <width> <height>"` while others (application-x-delta, application-x-executable, application-x-squashfs-image, apply) use  `viewBox="<width> <height>"`
Using [viewBox="<min-x> <min-y> <width> <height>"](https://sarasoueidan.com/blog/svg-coordinate-systems/#viewbox-syntax) you basically zoom the image and it may give problems to some apps or settings adhering to the protocols more strictly.
You may want to use `viewbox` instead or just `viewBox="<width> <height>"`

**Comment by 01micko** [comment]
Ok, I understand the problem, but remember these are _source_ icons. It all gets changed down the track. Any line beginning with `<svg ...` is replaced in `build_theme`. 

I'll eventually do something about it but it is not of high priority.

**Comment by mavrothal** [comment]
Actually, is not clear why viewbox is needed at all in these icons. 😮 
Is not like the icons cover only part of the svg or we want to show part of the icon.

**Comment by 01micko** [comment]
Did you build the icons? That is where it becomes important. The source icons case (that is, the ones you see in GitHub) are irrelevant to the end product.
